### ISSUE TITLE
لا يكمل التحديث يوجد مرفق

### ISSUE THREAD

**Issue by khalidmas** [kleeja-official/kleeja#147]
السلام عليكم 

بالمرفقات 

مالحل ؟

**Comment by khalidmas** [comment]
![Untitled](https://user-images.githubusercontent.com/36202324/79550668-59a07780-80a1-11ea-9acb-7476f2234763.jpg)

**Comment by MitanOmar** [comment]
url ??

**Comment by khalidmas** [comment]
www.z4z6.com

**Comment by khalidmas** [comment]
Kleeja error:

[ No Template ! ]

Requested "admin_php_info" template doesnt exist!

Visit Kleeja Website for more details.

**Comment by MitanOmar** [comment]
> Kleeja error:
> 
> [ No Template ! ]
> 
> Requested "admin_php_info" template doesnt exist!
> 
> Visit Kleeja Website for more details.

maybe you played with the code, because there is not template called `admin_php_info`,
your kleeja is defined as `http`  and your server is forcing the call to be https so the resources is not loaded in the page,
make the url in the database to https via phpmyadmin -> klj_config -> siteurl = https://z4z6.com/up/
and make the cookie_secure = 1

**Comment by khalidmas** [comment]
no modification

i do it same in siteurl

plz

**Comment by MitanOmar** [comment]
تعال ع الديسكورد https://discord.gg/Mp3XVKP
