### ISSUE TITLE
can you please update kleeja script 

### ISSUE THREAD

**Issue by Mustafa6699** [kleeja-official/kleeja#206]
can you please 
-update kleeja to support latest php 8.1.4
-use the new framework latest bootstrap 5.1.3
-update plugins 
-update theme
-use a more advanced UI
-can you add features as much as you can
-you can see this a file hosting script "https://yetishare.com"
-bro I want to contribute to this script but I am still junior at programming

**Comment by MitanOmar** [comment]
@Mustafa6699 
KLEEJA is free software, and it need someone to give it all his time to make it as you thinking about.
i am enjoying so much when developing kleeja, and it's a lot of fun. BUT i can not give it all my time, because there is noting that we got from developing kleeja. that's why i am only adding new features, and fixing the bugs on my free time.
