### ISSUE TITLE
This problem appears

### ISSUE THREAD

**Issue by MrMahmoudos** [kleeja-official/kleeja#236]
After creating the database and uploading the script, this problem appears, and I do not know what the reason is

![Screenshot_7](https://github.com/user-attachments/assets/477b2181-1176-4824-99a8-3fb19f38db24)

**Comment by RouatbiH** [comment]
[This ](https://github.com/kleeja-official/kleeja/issues/228#issuecomment-1703763013) comment will fix your issue.
Otherwise if you can not open the admin dashboard, then using `phpmyadmin` open the kleeja database, and from the config table, find a row with setting name called `siteurl`, change the setting value to start with `https://`.

**Comment by MrMahmoudos** [comment]
**A new problem appears during installation**
![Uploading Screenshot_7.png…]()

**Comment by RouatbiH** [comment]
@MrMahmoudos There is a problem with the attached image.
You can join us on [Discord](https://discord.gg/Mp3XVKP) for chat support.
